version: '3.8'

services:
  redis-node1:
    image: bitnami/redis:6.0.16
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --bind 0.0.0.0 --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --maxmemory 5mb --maxmemory-policy allkeys-lru --appendonly yes --port 7000 --dir /bitnami/redis/data
    ports:
      - "7000:7000"
    volumes:
      - ./redis-node1-data:/data
    networks:
      - redis-cluster-net
  redis-node2:
    image: bitnami/redis:6.0.16
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --bind 0.0.0.0 --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --maxmemory 5mb --maxmemory-policy allkeys-lru --appendonly yes --port 7001 --dir /bitnami/redis/data
    ports:
      - "7001:7001"
    volumes:
      - ./redis-node2-data:/data
    networks:
      - redis-cluster-net
  redis-node3:
    image: bitnami/redis:6.0.16
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --bind 0.0.0.0 --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --maxmemory 5mb --maxmemory-policy allkeys-lru --appendonly yes --port 7002 --dir /bitnami/redis/data
    ports:
      - "7002:7002"
    volumes:
      - ./redis-node3-data:/data
    networks:
      - redis-cluster-net
  database:
    restart: always
    image: bitnami/postgresql:11
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - type: bind
        source: ./db/data/postgres
        target: /var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - redis-cluster-net
  backend:
    depends_on:
      - redis-node1
      - database
      - grcpsv
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=database
      - PORT=$BACKEND_PORT
      - REDIS_HOST=redis-node1
    volumes:
      - ./backend/index.js:/home/node/index.js
      - ./backend/example.proto:/home/node/example.proto
      - ./backend/grpc_client.js:/home/node/grpc_client.js
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    networks:
      - redis-cluster-net
  grcpsv:
    depends_on:
      - redis-node1
      - database
    restart: always
    build:
      context: ./backend/grpcsv
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=database
      - PORT=5000
      - REDIS_HOST=redis-node1
    volumes:
      - ./backend/grpcsv/index.js:/home/node/index.js
      - ./backend/grpcsv/example.proto:/home/node/example.proto
      - ./backend/grpcsv/data.json:/home/node/data.json
      - ./backend/grpcsv/grpc_server.js:/home/node/grpc_server.js
    ports:
      - "5000:5000"
      - "4500:4500"
    networks:
      - redis-cluster-net
  frontend:
    depends_on:
      - database
      - backend
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - REACT_APP_BACKEND_PORT=$BACKEND_PORT
      - REACT_APP_BACKEND_HOST=backend
      - PORT=$FRONTEND_PORT
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"

networks:
  redis-cluster-net:
    driver: bridge

volumes:
  redis-node1-data:
  redis-node2-data:
  redis-node3-data: