version: '3.8'

services:
  redis-master:
    image: bitnami/redis:6.0.16
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --bind 0.0.0.0 --maxmemory 7mb --maxmemory-policy allkeys-lru --dir /bitnami/redis/data
    volumes:
      - './redis_master_data:/bitnami/redis/data'
    ports:
      - "6379:6379"
    networks:
      - redis-network
  redis-replica1:
    image: bitnami/redis:6.0.16
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
    depends_on:
      - redis-master
    volumes:
      - './redis_replica1_data:/bitnami/redis/data'
    networks:
      - redis-network
  redis-replica2:
    image: bitnami/redis:6.0.16
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
    depends_on:
      - redis-master
    volumes:
      - './redis_replica2_data:/bitnami/redis/data'
    networks:
      - redis-network

  database:
    restart: always
    image: bitnami/postgresql:11
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - type: bind
        source: ./db/data/postgres
        target: /var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - redis-network
  backend:
    depends_on:
      - redis-master
      - database
      - grcpsv
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=database
      - PORT=$BACKEND_PORT
      - REDIS_HOST=redis-master
    volumes:
      - ./backend/index.js:/home/node/index.js
      - ./backend/example.proto:/home/node/example.proto
      - ./backend/grpc_client.js:/home/node/grpc_client.js
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    networks:
      - redis-network
  grcpsv:
    depends_on:
      - redis-master
      - database
    restart: always
    build:
      context: ./backend/grpcsv
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=database
      - PORT=5000
      - REDIS_HOST=redis-master
    volumes:
      - ./backend/grpcsv/index.js:/home/node/index.js
      - ./backend/grpcsv/example.proto:/home/node/example.proto
      - ./backend/grpcsv/data.json:/home/node/data.json
      - ./backend/grpcsv/grpc_server.js:/home/node/grpc_server.js
    ports:
      - "5000:5000"
      - "4500:4500"
    networks:
      - redis-network
  frontend:
    depends_on:
      - database
      - backend
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - REACT_APP_BACKEND_PORT=$BACKEND_PORT
      - REACT_APP_BACKEND_HOST=backend
      - PORT=$FRONTEND_PORT
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"

networks:
  redis-network:
    driver: bridge

volumes:
  redis_master_data:
  redis_replica1_data:
  redis_replica2_data: